# Generated by Django 3.2.25 on 2026-01-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(default='N/A', max_length=20),
            preserve_default=False,
        ),
    ]
