# Generated by Django 3.2.25 on 2026-02-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='product_variant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
