# Generated by Django 5.1.6 on 2026-02-12 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactinquiry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactInquiry',
            new_name='ContactEnquiry',
        ),
    ]
